# Generated by Django 5.1 on 2025-12-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticsearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('query_body', models.JSONField()),
                ('index_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Elasticsearch Query',
                'verbose_name_plural': 'Elasticsearch Queries',
                'db_table': 'elasticsearch_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('records_count', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
                'db_table': 'file_upload_history',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
